### PR TITLE
dont attempt to munge msids

### PR DESCRIPTION
**Pull request by fippo**
reverts #8 for now because https://bugs.chromium.org/p/webrtc/issues/detail?id=5624

@xdumaine @legastero: I think we should not attempt to do this because a=msid should take preference and I don't want chrome to prioritize the legacy thing.

### CODE REVIEW

**Comment by legastero** [comment]
I'm going to have to test this on Talky. I _think_ we only bothered to do this because Chrome was providing unlabeled streams when coming from Firefox, which messed up our stream storage & tracking.

**Comment by fippo** [comment]
maybe use stream.id instead of stream.label? I think label is legacy

**Comment by legastero** [comment]
I'll need to test again with the current browser versions, but I do remember at the time that Chrome would happily emit streams with neither an id nor a label if they came from Firefox.

**Comment by xdumaine** [comment]
I'm out today and won't be able to check this. Will forward to my team to check it out.

**Comment by fippo** [comment]
uh... did we decide what to do here?

**Comment by xdumaine** [comment]
I think the chrome team addressed the problem that this was fixing but it might be good to do this anyway.

**Comment by fippo** [comment]
right, lets don't do this then. Thanks for the reminder

**Pull request closed without merging**
